[package]
name = "hash-types"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bimap = "0.6"
derive_more = "0.99"
indexmap = "1.9"
log = "0.4"
num-bigint = "0.4"
textwrap = "0.16"
utility-types = "0.0.2"

hash-ast = { path = "../hash-ast" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
