[package]
name = "hash-types"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
log = "0.4"
num-bigint = "0.4"
utility-types = "0.0.2"
indexmap = "1.9"

hash-ast = { path = "../hash-ast" }
hash-utils = { path = "../hash-utils" }
hash-source = { path = "../hash-source" }
