[package]
name = "hash-source"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
bimap = { workspace = true }
bytecount = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
line-span = { workspace = true }
derive_more = { workspace = true }

hash-storage = { workspace = true }
hash-target = { workspace = true }
hash-utils = { workspace = true }
