[package]
name = "hash-source"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bimap = "0.6.2"
dashmap = "5.1"
derive_more = "0.99"
fnv = "1.0.7"
lazy_static = "1.4.0"
num-bigint = "0.4"
once_cell = "1.17"
bytecount = "0.6.3"

hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" } 
