[package]
name = "hash-source"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
thiserror = "1.0"
lazy_static = "1.4.0"
slotmap = "1.0"
derive_more = "0.99"
hash-utils = { path = "../hash-utils" }
