[package]
name = "hash-semantics"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bimap = "0.6"
dashmap = "5.1"
derive_more = "0.99"
num-bigint = "0.4"
once_cell = "1.17"
bitflags = "2.0.0-rc.1"

hash-ast = { path = "../hash-ast" }
hash-error-codes = { path = "../hash-error-codes" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-tree-def = { path = "../hash-tree-def" }
hash-tir = { path = "../hash-tir" }
hash-utils = { path = "../hash-utils" }
hash-intrinsics = { path = "../hash-intrinsics" }
hash-typecheck = { path = "../hash-typecheck" }
hash-target = { path = "../hash-target" }
hash-exhaustiveness = { path = "../hash-exhaustiveness" }
