[package]
name = "hash-lower"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
index_vec = "0.1.3"
rayon = "1.5.0"
smallvec = "1.9.0"
num-traits = "0.2.15"
indexmap = "1.9"
fixedbitset = "0.4.2"

hash-ast = { path = "../hash-ast" }
hash-tree-def = { path = "../hash-tree-def" }
hash-ir = { path = "../hash-ir" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-types = { path = "../hash-types" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
