[package]
name = "hash-lower"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
index_vec = "0.1.3"
rayon = "1.5.0"

hash-ast = { path = "../hash-ast" }
hash-ir = { path = "../hash-ir" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-types = {  path = "../hash-types" }
hash-utils = { path = "../hash-utils" }
