[package]
name = "hash-lower"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
fixedbitset = "0.4.2"
indexmap = "1.9"
num-traits = "0.2.15"
rayon = "1.5.0"
smallvec = "1.9.0"

hash-ast = { path = "../hash-ast" }
hash-ir = { path = "../hash-ir" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-layout = { path = "../hash-layout" }
hash-target = { path = "../hash-target" }
hash-tree-def = { path = "../hash-tree-def" }
hash-tir = { path = "../hash-tir" }
hash-utils = { path = "../hash-utils" }
hash-semantics = { path = "../hash-semantics" }
