[package]
name = "hash-backend"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
hash-parser = {path = "../hash-parser" } 
rustyline = "8.0.0"
thiserror = "1.0"
