[package]
name = "hash-tir"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
num_enum = { workspace = true }
paste = { workspace = true }
textwrap = { workspace = true }
typed-builder = { workspace = true }
utility-types = { workspace = true }
derive_more = { workspace = true }

hash-ast = { workspace = true }
hash-ast-utils = { workspace = true }
hash-const-eval = { workspace = true }
hash-repr = { workspace = true }
hash-reporting = { workspace = true }
hash-source = { workspace = true }
hash-storage = { workspace = true }
hash-target = { workspace = true }
hash-utils = { workspace = true }
