[package]
name = "hash-tir"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bimap = "0.6"
derive_more = "0.99"
indexmap = "1.9"
num-bigint = "0.4"
textwrap = "0.16"
utility-types = "0.0.2"
typed-builder = "0.11"
lazy_static = "1.4"

hash-ast = { path = "../hash-ast" }
hash-source = { path = "../hash-source" }
hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
