[package]
name = "hash-tir"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
derive_more = "0.99"
num-bigint = "0.4"
textwrap = "0.16"
utility-types = "0.0.2"
typed-builder = "0.11"

hash-ast = { path = "../hash-ast" }
hash-source = { path = "../hash-source" }
hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
hash-reporting = { path = "../hash-reporting" }
