[package]
name = "hash-tir"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
num_enum = "0.5"
num-bigint = "0.4"
paste = "1.0"
textwrap = "0.16"
typed-builder = "0.11"
utility-types = "0.0.2"

hash-ast = { path = "../hash-ast" }
hash-ast-utils = { path = "../hash-ast-utils" }
hash-const-eval = { path = "../hash-const-eval" }
hash-layout = { path = "../hash-layout" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
