[package]
name = "hash-utils"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
append-only-vec = "0.1"
arrayvec = "0.7.2"
fixedbitset = "0.4.2"
fxhash = "0.2.1"
index_vec = "0.1.3"
itertools = "0.10.5"
num-traits = "0.2"
log = "0.4"
smallvec = "1.9.0"
stacker = "0.1.15"
thin-vec = "0.2.10"
dashmap = "5.1"
parking_lot = "0.12"
