[package]
name = "hash-utils"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
backtrace = "0.3"
bitflags = "2.4.0"
crossbeam-channel = "0.5.1"
dashmap = "5.1"
fixedbitset = "0.4.2"
fxhash = "0.2.1"
index_vec = "0.1.3"
indexmap = "1.9"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4"
num-traits = "0.2"
parking_lot = "0.12"
rayon = "1.5.0"
smallvec = "1.11.0"
stacker = "0.1.15"
thin-vec = "0.2.10"
