[package]
name = "hash-utils"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
append-only-vec = "0.1"
log = "0.4"
stacker = "0.1.15"
fixedbitset = "0.4.2"
fxhash = "0.2.1"
index_vec = "0.1.3"
smallvec = "1.9.0"
