[package]
name = "hash-utils"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
arrayvec = "0.7.2"
backtrace = "0.3"
bitflags = "2.4.0"
clap = { version = "4.3.8", features = ["derive"] }
crossbeam-channel = "0.5.1"
dashmap = "5.1"
derive_more = "0.99"
fixedbitset = "0.4.2"
fnv = "1.0.7"
fxhash = "0.2.1"
index_vec = "0.1.3"
indexmap = "1.9"
itertools = "0.10.5"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1.17"
parking_lot = "0.12"
rayon = "1.5.0"
schemars = "0.8.16"
serde = { version = "1.0.202", features = ["derive"] }
smallvec = "1.11.0"
stacker = "0.1.15"
thin-vec = "0.2.10"

[target.'cfg(windows)'.dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
]

