[package]
name = "hash-reporting"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
thiserror = "1.0"
hash-source = {path = "../hash-source" }
hash-alloc = {path = "../hash-alloc" }
hash-error-codes = {path = "../hash-error-codes" }
hash-utils = {path = "../hash-utils" }
