[package]
name = "hash-reporting"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
thiserror = "1.0"
hash-ast = {path = "../hash-ast" }
hash-alloc = {path = "../hash-alloc" }
