[package]
name = "hash-reporting"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
hash-error-codes = { path = "../hash-error-codes" }
hash-source = { path = "../hash-source" }
hash-utils = { path = "../hash-utils" }
hash-target = { path = "../hash-target" }

unicode-normalization = "0.1.22"
unicode-width = "0.1.8"
