[package]
name = "hash-reporting"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
unicode-normalization = { workspace = true }

hash-error-codes = { workspace = true }
hash-source = { workspace = true }
hash-utils = { workspace = true }
hash-target = { workspace = true }

