[package]
name = "hash-codegen-llvm"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
rayon = "1.5.0"
llvm-sys = "150.0.3"
fxhash = "0.2.1"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0"] }

hash-codegen = {path = "../hash-codegen" }
hash-ir = {path = "../hash-ir" }
hash-source = {path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-utils = {path = "../hash-utils" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
