[package]
name = "hash-codegen"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
rayon = "1.5.0"

hash-ir = {path = "../hash-ir" }
hash-utils = {path = "../hash-utils" }
hash-source = {path = "../hash-source" }
hash-target = { path = "../hash-target" }
