[package]
name = "hash-codegen"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
fixedbitset = "0.4.2"
rayon = "1.5.0"

hash-abi = {path = "../hash-abi" }
hash-ir = {path = "../hash-ir" }
hash-layout = {path = "../hash-layout" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = {path = "../hash-source" }
hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-utils = {path = "../hash-utils" }
