[package]
name = "hash-pest-parser"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
log = "0.4"
lazy_static = "1.4.0"
crossbeam-channel = "0.5.1"
rayon = "1.5.0"
pest = "2.1"
pest_derive = "2.1"
hash-ast = {path = "../hash-ast" }
hash-alloc = {path = "../hash-alloc" }
hash-utils = {path = "../hash-utils" }
derive_more = "0.99"
