[package]
name = "hash-ast-desugaring"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
rayon = "1.5.0"

hash-ast = { path = "../hash-ast" }
hash-tree-def = { path = "../hash-tree-def" }
hash-source = { path = "../hash-source" }
hash-reporting = { path = "../hash-reporting" }
hash-pipeline = { path = "../hash-pipeline" }
