[package]
name = "hashc"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"
default-run = "hashc"

[[bin]]
name = "hashc"
path = "./src/main.rs"

[dependencies]
profiling = { workspace = true }
tracy-client = { workspace = true }

hash-ast = { workspace = true }
hash-pipeline = { workspace = true }
hash-reporting = { workspace = true }
hash-driver = { workspace = true }
hash-source = { workspace = true }
hash-target = { workspace = true }
hash-utils = { workspace = true }

[features]
tracy = ["profiling/profile-with-tracy"]
llvm = ["hash-pipeline/llvm", "hash-driver/llvm"]

default = ["llvm"]

[dev-dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [
  "precommit-hook",
  "run-for-all",
  "run-cargo-test",
  "run-cargo-fmt",
  "run-cargo-clippy",
]
