[package]
name = "hash"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"
default-run = "hash"

[dependencies]
thiserror = "1.0"
log = "0.4"
backtrace = "0.3"
num_cpus = "1.13.0"
rayon = "1.5.0"
clap = { version = "3.0.0", features = ["derive"] }

profiling = "1.0.6"
tracy-client = "0.13.2"

hash-alloc = { path = "../hash-alloc" }
hash-source = { path = "../hash-source" }
hash-interactive = { path = "../hash-interactive" }
hash-reporting = { path = "../hash-reporting" }
hash-pipeline = { path = "../hash-pipeline" }
hash-tree-def = { path = "../hash-tree-def" }

# Various stages that the pipeline interfaces with...
hash-parser = { path = "../hash-parser" }
hash-ast-desugaring = { path = "../hash-ast-desugaring" }
hash-untyped-semantics = { path = "../hash-untyped-semantics" }
hash-typecheck = { path = "../hash-typecheck" }
hash-lower = { path = "../hash-lower" }
hash-vm = { path = "../hash-vm" }

[features]
profile-with-tracy = ["profiling/profile-with-tracy"]

# Enable this flag to run tracy profiling
# default = ["profile-with-tracy"]

[dev-dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [
  "precommit-hook",
  "run-for-all",
  "run-cargo-test",
  "run-cargo-fmt",
  "run-cargo-clippy",
]
