[package]
name = "hash"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"
default-run = "hash"

[dependencies]
backtrace = "0.3"
clap = { version = "4.0.29", features=["derive"] }
log = "0.4"
num_cpus = "1.13.0"
profiling = "1.0.6"
rayon = "1.5.0"
tracy-client = "0.13.2"

hash-alloc = { path = "../hash-alloc" }
hash-ast = { path = "../hash-ast" }
hash-interactive = { path = "../hash-interactive" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-session = { path = "../hash-session" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-tree-def = { path = "../hash-tree-def" }

[features]
profile-with-tracy = ["profiling/profile-with-tracy"]

# Enable this flag to run tracy profiling
# default = ["profile-with-tracy"]

[dev-dependencies.cargo-husky]
version = "1.5"
default-features = false
features = [
  "precommit-hook",
  "run-for-all",
  "run-cargo-test",
  "run-cargo-fmt",
  "run-cargo-clippy",
]
