[package]
name = "hash-ast-utils"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
hash-ast = { path = "../hash-ast" }
hash-fmt = { path = "../hash-fmt" }
hash-source = { path = "../hash-source" }
hash-utils = { path = "../hash-utils" }
