[package]
name = "hash-repr"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
fixedbitset = "0.4.2"
paste = "1.0.14"

hash-ast = { path = "../hash-ast" }
hash-storage = { path = "../hash-storage" }
hash-target = { path = "../hash-target" }
hash-source = { path = "../hash-source" }
hash-utils = { path = "../hash-utils" }
hash-reporting = { path = "../hash-reporting" }
