[package]
name = "hash-token"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
derive_more = "0.99"
strum_macros = "0.21"
smallvec = "1.9.0"

hash-alloc = {path = "../hash-alloc" }
hash-source = {path = "../hash-source" }
