[package]
name = "hash-token"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
strum_macros = "0.21"
smallvec = "1.9.0"

hash-source = {path = "../hash-source" }
