[package]
name = "hash-token"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
num-derive = { workspace = true }
num-traits = { workspace = true }
strum_macros = { workspace = true }
phf = { workspace = true }

hash-utils = { workspace = true }
hash-source = { workspace = true }
