[package]
name = "hash-token"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
strum_macros = "0.21"

hash-utils = { path = "../hash-utils" }
hash-source = {path = "../hash-source" }
