[package]
name = "hash-interactive"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
hash-ast = {path = "../hash-ast" }
hash-parser = {path = "../hash-parser" }
hash-reporting = {path = "../hash-reporting" }
hash-alloc = {path = "../hash-alloc" }
hash-pest-parser = {path = "../hash-pest-parser", optional = true }
rustyline = "8.0.0"

[features]
use-pest = []

# default = ["use-pest"]
