[package]
name = "hash-interactive"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
hash-ast = {path = "../hash-ast" }
hash-reporting = {path = "../hash-reporting" }
hash-pest-parser = {path = "../hash-pest-parser" }
rustyline = "8.0.0"
