[package]
name = "hash-interactive"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
hash-ast = {path = "../hash-ast" }
hash-parser = {path = "../hash-parser" }
hash-reporting = {path = "../hash-reporting" }
hash-alloc = {path = "../hash-alloc" }
hash-typecheck = {path = "../hash-typecheck" }
rustyline = "8.0.0"
