[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
slotmap = "1.0"
dashmap = "4.0"

hash-ast = { path = "../hash-ast" }
hash-source = { path = "../hash-source" }
hash-utils = { path = "../hash-utils" }
hash-alloc = { path = "../hash-alloc" }
hash-reporting = {path = "../hash-reporting" }
hash-pipeline = {path = "../hash-pipeline" }
