[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
hash-ast = { path = "../hash-ast" }
hash-utils = { path = "../hash-utils" }
hash-alloc = { path = "../hash-alloc" }
smallvec = { version = "1.6", features = ["union"] }
slotmap = "1.0"
dashmap = "4.0"
