[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
itertools = "0.10"
num-bigint = "0.4"
once_cell = "1.17"

hash-ast = { path = "../hash-ast" }
hash-ast-utils = { path = "../hash-ast-utils" }
hash-attrs = { path = "../hash-attrs" }
hash-exhaustiveness = { path = "../hash-exhaustiveness" }
hash-reporting = { path = "../hash-reporting" }
hash-layout = { path = "../hash-layout" }
hash-pipeline = { path = "../hash-pipeline" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-storage = { path = "../hash-storage" }
hash-tir = { path = "../hash-tir" }
hash-tree-def = { path = "../hash-tree-def" }
hash-utils = { path = "../hash-utils" }
