[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bimap = "0.6"
dashmap = "5.1"
derive_more = "0.99"
if_chain = "1.0.2"
itertools = "0.10"
log = "0.4"
num-bigint = "0.4"
rayon = "1.5.0"
slotmap = "1.0"
smallvec = "1.9"
once_cell = "1.17"

hash-alloc = { path = "../hash-alloc" }
hash-ast = { path = "../hash-ast" }
hash-error-codes = { path = "../hash-error-codes" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-tree-def = { path = "../hash-tree-def" }
hash-tir = { path = "../hash-tir" }
hash-utils = { path = "../hash-utils" }
hash-intrinsics = { path = "../hash-intrinsics" }
