[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
log = "0.4"
slotmap = "1.0"
dashmap = "5.1"
itertools = "0.10"
if_chain = "1.0.2"
num-bigint = "0.4"
smallvec = "1.9.0"
rayon = "1.5.0"

hash-ast = { path = "../hash-ast" }
hash-alloc = { path = "../hash-alloc" }
hash-ast-desugaring = { path = "../hash-ast-desugaring" }
hash-error-codes = { path = "../hash-error-codes" }
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-types = { path = "../hash-types" }
hash-utils = { path = "../hash-utils" }
