[package]
name = "hash-typecheck"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
dashmap = "5.1"
derive_more = "0.99"
itertools = "0.10"
num-bigint = "0.4"
once_cell = "1.17"

hash-ast = { path = "../hash-ast" }
hash-error-codes = { path = "../hash-error-codes" }
hash-exhaustiveness = { path = "../hash-exhaustiveness" }
hash-intrinsics = { path = "../hash-intrinsics" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-storage = { path = "../hash-storage" }
hash-tir = { path = "../hash-tir" }
hash-tree-def = { path = "../hash-tree-def" }
hash-utils = { path = "../hash-utils" }
