[package]
name = "hash-typechecker"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
hash-ast = { path = "../hash-ast" }
hash-utils = { path = "../hash-utils" }
smallvec = { version = "1.6", features = ["union"] }
dashmap = "4.0"
