//! Hash Parser diagnostic utilities, error and warning definitions.
//! This module contains all of the logic that provides diagnostic
//! capabilities within the parser.
pub(crate) mod error;
pub(crate) mod warning;

use hash_reporting::{diagnostic::Diagnostics, report::Report, reporter::Reports};

use self::{
    error::ParseError,
    warning::{ParseWarning, ParseWarningWrapper},
};
use crate::parser::AstGen;

/// Represents the stored diagnostics within the parser.
#[derive(Default)]
pub struct ParserDiagnostics {
    /// Errors generated by the parser.
    pub(crate) errors: Vec<ParseError>,
    /// Warnings generated by the parser.
    pub(crate) warnings: Vec<ParseWarning>,
}

impl<'stream, 'resolver> Diagnostics<ParseError, ParseWarning> for AstGen<'stream, 'resolver> {
    type DiagnosticsStore = ParserDiagnostics;

    fn diagnostic_store(&self) -> &Self::DiagnosticsStore {
        &self.diagnostics
    }

    fn add_error(&mut self, error: ParseError) {
        self.diagnostics.errors.push(error);
    }

    fn add_warning(&mut self, warning: ParseWarning) {
        self.diagnostics.warnings.push(warning);
    }

    fn has_errors(&self) -> bool {
        !self.diagnostic_store().errors.is_empty()
    }

    fn has_warnings(&self) -> bool {
        !self.diagnostic_store().warnings.is_empty()
    }

    fn into_reports(self) -> Vec<Report> {
        self.diagnostics
            .errors
            .into_iter()
            .flat_map(Reports::from)
            .chain(self.diagnostics.warnings.into_iter().flat_map(|warn| {
                Reports::from(ParseWarningWrapper(warn, self.resolver.current_source_id()))
            }))
            .collect()
    }

    fn into_diagnostics(self) -> (Vec<ParseError>, Vec<ParseWarning>) {
        (self.diagnostics.errors.to_vec(), self.diagnostics.warnings)
    }

    fn merge_diagnostics(&mut self, other: impl Diagnostics<ParseError, ParseWarning>) {
        let (errors, warnings) = other.into_diagnostics();

        self.diagnostics.errors.extend(errors);
        self.diagnostics.warnings.extend(warnings);
    }
}
