[package]
name = "hash-messaging"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
hash-utils = {path = "../hash-utils" }
hash-reporting = {path = "../hash-reporting" }
