[package]
name = "hash-ir"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
fixedbitset = "0.4.2"
html-escape = "0.2.12"
index_vec = "0.1.3"
smallvec = "1.9.0"

hash-alloc = { path = "../hash-alloc" }
hash-ast = { path = "../hash-ast" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-tir = { path = "../hash-tir" }
hash-utils = { path = "../hash-utils" }
