[package]
name = "hash-ir"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
hash-utils = {path = "../hash-utils" }
hash-alloc = {path = "../hash-alloc" }
hash-source = {path = "../hash-source" }
