[package]
name = "hash-storage"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
bumpalo = { workspace = true }
bumpalo-herd = { workspace = true }
dashmap = { workspace = true }
fxhash = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
