[package]
name = "hash-scope-check"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
doctest = false

[dependencies]
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-ast = { path = "../hash-ast" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
hash-ast-utils = { path = "../hash-ast-utils" }
hash-tree-def = { path = "../hash-tree-def" }
hash-pipeline = { path = "../hash-pipeline" }
