[package]
name = "hash-link"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
hash-pipeline = { path = "../hash-pipeline" }
hash-reporting = { path = "../hash-reporting" }
hash-utils = { path = "../hash-utils" }
