[package]
name = "hash-tree-def"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4"
proc-macro-error = "1.0.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }
