[package]
name = "hash-tree-def"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true
doctest = false

[dependencies]
convert_case = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
