[package]
name = "hash-abi"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
index_vec = "0.1.3"

hash-ir = {path = "../hash-ir" }
hash-layout = {path = "../hash-layout" }
hash-source = {path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-utils = {path = "../hash-utils" }
