[package]
name = "hash-ast"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
dashmap = "4.0"
fnv = "1.0.7"
hash-utils = { path = "../hash-utils" } 
hash-alloc = { path = "../hash-alloc" }
hash-source = { path = "../hash-source" }
