[package]
name = "hash-ast"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
lazy_static = "1.4.0"
crossbeam-channel = "0.5.1"
num_cpus = "1.13.0"
rayon = "1.5.0"
thiserror = "1.0"
num = "0.4"
closure = "0.3.0"
hash-utils = { path = "../hash-utils" }
hash-utils-testing-macros = { path = "../hash-utils/testing-macros" }
dashmap = "4.0"
