[package]
name = "hash-ast"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"] }
lazy_static = "1.4.0"
crossbeam-channel = "0.5.1"
num_cpus = "1.13.0"
rayon = "1.5.0"
thiserror = "1.0"
dashmap = "4.0"
strum = "0.21"
strum_macros = "0.21"
derive_more = "0.99"
parking_lot = "0.11"
hash-utils = { path = "../hash-utils" }
hash-utils-testing-macros = { path = "../hash-utils/testing-macros" }
hash-alloc = { path = "../hash-alloc" }
