[package]
name = "hash-ast"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
replace_with = "0.1.7"
num-bigint = "0.4"

hash-utils = { path = "../hash-utils" } 
hash-source = { path = "../hash-source" }
