[package]
name = "hash-pipeline"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
const_format = "0.2.30" # for concatenating strings together at compile time.
num_cpus = "1.13.0"
clap = { version = "4.3.8", features = ["derive"] }

hash-ast = { path = "../hash-ast" }
hash-fmt = { path = "../hash-fmt" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-utils = { path = "../hash-utils" }
