[package]
name = "hash-pipeline"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
const_format = { workspace = true }
num_cpus = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

hash-ast = { workspace = true }
hash-ast-utils = { workspace = true }
hash-reporting = { workspace = true }
hash-source = { workspace = true }
hash-target = { workspace = true }
hash-utils = { workspace = true }


[features]
llvm = []
