[package]
name = "hash-pipeline"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
bitflags = "2.0.0-rc.1"
const_format = "0.2.30" # for concatenating strings together at compile time.
num_cpus = "1.13.0"
rayon = "1.5.0"
slotmap = "1.0"

hash-ast = { path = "../hash-ast" }
hash-reporting = { path = "../hash-reporting" }
hash-source = { path = "../hash-source" }
hash-target = { path = "../hash-target" }
hash-tir = { path = "../hash-tir" }
hash-utils = { path = "../hash-utils" }
