[package]
name = "hash-pipeline"
version = "0.1.0"
authors = ["The Hash Language authors"]
edition = "2021"

[dependencies]
log = "0.4"
slotmap = "1.0"
rayon = "1.5.0"
num_cpus = "1.13.0"
bitflags = "1.3.2"

# For deriving commonly shared data structures between the settings 
# and option parsing for commandline.
clap = "4.0.29"
clap_derive = "4.0.21"

hash-ast = { path = "../hash-ast" }
hash-types = { path = "../hash-types" }
hash-utils = { path = "../hash-utils" }
hash-source = { path = "../hash-source" }
hash-reporting = { path = "../hash-reporting" }
hash-target = { path = "../hash-target" }
